# Generated by Django 3.1.5 on 2021-01-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=10)),
                ('annual_rainfall', models.CharField(max_length=20)),
                ('farming_system', models.CharField(max_length=200)),
                ('len_of_growing_period', models.CharField(max_length=15)),
                ('altitute', models.CharField(max_length=15)),
                ('erosion_hazard', models.CharField(max_length=15)),
                ('dominant_soil', models.CharField(max_length=100)),
                ('ph_top_soil', models.CharField(max_length=10)),
                ('water_holding_capacity', models.CharField(max_length=20)),
            ],
        ),
    ]
