# Generated by Django 3.1.5 on 2021-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='altitute',
            field=models.CharField(max_length=15, verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='annual_rainfall',
            field=models.CharField(max_length=20, verbose_name='Annual Rainfall (mm)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='len_of_growing_period',
            field=models.CharField(max_length=15, verbose_name='Length of growing period'),
        ),
    ]
