# Generated by Django 3.1.5 on 2021-01-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0002_auto_20210126_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_info.region')),
            ],
        ),
    ]
