# Generated by Django 3.1.5 on 2021-02-04 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0004_auto_20210204_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('seed_type_irrigation', models.CharField(max_length=50)),
                ('seed_type_dry_land', models.CharField(max_length=50)),
                ('pestcides', models.CharField(max_length=50)),
                ('fertilizer', models.CharField(max_length=50)),
                ('labour', models.CharField(max_length=50)),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_info.region')),
            ],
        ),
    ]
