# Generated by Django 3.1.5 on 2021-02-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0005_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='price_per_hectare',
            field=models.CharField(default=2000, max_length=20),
            preserve_default=False,
        ),
    ]
