# Generated by Django 3.1.5 on 2021-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0006_crop_price_per_hectare'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
    ]
