# Generated by Django 3.1.6 on 2021-02-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0007_auto_20210212_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='seed_type_dry_land',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='seed_type_irrigation',
            field=models.CharField(max_length=100),
        ),
    ]
