# Generated by Django 3.1.6 on 2021-03-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming_info', '0008_auto_20210226_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='district_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='farming_info.district'),
            preserve_default=False,
        ),
    ]
